export interface Product {
    _id:string;
    title:string;
    _type:"product";
    productImage?:{
        asset:{
            _ref:string;
            _type:"image"
        }
    };
    price:number;
    description?:string;
    tags:string[];
    isNew:boolean;
    inventory:number;
    discountedPrice:number;
    slug:{
        _type:"slug";
        current:string
    };
}